# Generated by Django 3.2 on 2022-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20221024_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(max_length=20, verbose_name='Nombre Corto'),
        ),
    ]
