# Generated by Django 3.2 on 2022-11-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_alter_departamento_shor_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
    ]
