# Generated by Django 3.2 on 2022-11-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prueba_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
