# Generated by Django 3.2 on 2022-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(default='', max_length=60, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(default='', max_length=60, verbose_name='Apellidos'),
            preserve_default=False,
        ),
    ]
