# Generated by Django 3.2 on 2022-10-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
