# Generated by Django 3.2 on 2022-10-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_habilidades_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades Empleados'},
        ),
    ]
