# Generated by Django 3.2 on 2022-10-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleados'),
        ),
    ]
