# Generated by Django 3.2 on 2022-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_empleado_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres completos'),
        ),
    ]
