# Generated by Django 3.2 on 2022-11-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['first_name', 'last_name', 'full_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
    ]
