# Generated by Django 3.2 on 2022-11-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='full_name',
        ),
    ]
